### ISSUE TITLE
关于扫码时，识别速度慢（扫码慢、）的一个原因

### ISSUE THREAD

**Issue by Seachal** [bingoogolapple/QRCode#260]
关于扫码时，识别速度慢找到一个原因，和手机的性能有一定的关系。对于配置低一些的（例如努比亚 z9 mini）识别较慢，大概需要四五秒；用配置高一些的（例如小米5s），大概不到一秒。目前是根据这两部手机测试得出的结论，并不一定准确，不一定适用所有情况。

**Comment by SDKANDROID** [comment]
我现在也遇到这个问题了扫码的时候速度慢从相册识别条码的时候也慢，除了是手机性能的问题意外还有别的原因吗你解决了吗

**Comment by ypf168326** [comment]
小米4识别速度也挺慢的，和手机硬件配置是有关系的。

**Comment by Seachal** [comment]
@SDKANDROID   这里有一个可以运行的zxing的官方demo[zxing example](https://github.com/Seachal/zxing-android-official-demo)，在选项里面可以勾选一维码、二维码，只扫一种码的情况下，识别速度会有一定的提升，从4-5秒变成2-3秒的样子。  BGAQRCode-Android我感觉无论是选择扫条码还是扫二维码，是条码/二维码都可以扫。  可以试试修改BGAQRCode-Android使它只扫一种码。

**Comment by SDKANDROID** [comment]
@Seachal 好的谢谢了，我把那个识别延迟改了一下，扫描速度还可以，但是从相册识别的时候还是慢目前只是这一个手机这样其他的手机都没有问题

**Comment by Sabirjan** [comment]
我发现的扫码慢的原因是： public String processData(byte[] data, int width, int height, boolean isRetry) {
这个方法传过来的data 一般 2MB左右，图片过大，所以低端手机扫码慢

**Comment by NikiLee2016** [comment]
我偶然拿到了别人公司内部的一个扫码库, 同样的低端机那个库只需要1秒, 而bga需要四五秒...我觉得还是和识别算法有关系

**Comment by Sabirjan** [comment]
@NikiLee2016 分享一下，谢谢  253933559@qq.com

**Comment by ShawnAnn** [comment]
@NikiLee2016 求分享，1904508978@qq.com

**Comment by ypf168326** [comment]
@NikiLee2016 同上，925663059@qq.com

**Comment by Bertkiing** [comment]
@NikiLee2016 同上,非常感谢，2621376944@qq.com

**Comment by Sujie1** [comment]
@NikiLee2016 同上,非常感谢，1510845285@qq.com

**Comment by bingoogolapple** [comment]
@NikiLee2016 求个 PR

**Comment by TechPursuer** [comment]
同上,非常感谢，447425304@qq.com

**Comment by twlk-jzy** [comment]
同上,非常感谢，616655225@qq.com

**Comment by Bter** [comment]
@NikiLee2016 可否分享一下,非常感谢，997400559@qq.com

**Comment by a1265137718** [comment]
@NikiLee2016 可否分享一下，谢谢 1265137718@qq.com

**Comment by chimpan** [comment]
@NikiLee2016  可否分享一下，谢谢 344364459@qq.com

**Comment by messisgod** [comment]
@NikiLee2016  可否分享一下，遇到瓶颈了,感谢。fanatic_l@163.com

**Comment by nickalc** [comment]
@Seachal @NikiLee2016 能分享一下吗，谢谢393324432@qq.com

**Comment by flyinggor** [comment]
@NikiLee2016 可以分享一下这个扫码库吗，万分感谢！ 137619239@qq.com

**Comment by flyinggor** [comment]
@NikiLee2016 能分享下这个扫码库吗，万分感谢！137619239@qq.com

**Comment by flyinggor** [comment]
@NikiLee2016 能分享下这个扫码库吗，万分感谢！137619239@qq.com

**Comment by izozo** [comment]
@NikiLee2016 大哥 求分享 急 万分感谢！ 838645060@qq.com

**Comment by Sirhu173977450** [comment]
@NikiLee2016 同上,非常感谢，1510845285@qq.com

**Comment by snsdTJ** [comment]
@NikiLee2016 大哥求分享，我自己搞不定。 243843598@qq.com

**Comment by xiaoduv587** [comment]
@ NikiLee2016大哥求分享，我自己搞不定.1392229149 @ qq.com

**Comment by zyzhangyuan88** [comment]
@ NikiLee2016大哥求分享，472918259@qq.com

**Comment by liuqiangdd** [comment]
@NikiLee2016 大哥求分享，764247818@qq.com

**Comment by iszhaoqing** [comment]
@NikiLee2016 求分享，我此前用的是zbar库，但扫描速度还是慢，zhangzq787@163.com

**Comment by ypf168326** [comment]
支付宝和微信扫码那速度是贼快啊，不知道他们的算法是怎么实现的？

**Comment by ddong1031** [comment]
@NikiLee2016 求分享，扫描速度真的慢，尤其是灰度高的，840313601@qq.com

**Comment by chenxinfei** [comment]
@NikiLee2016 求分享，扫描速度真的慢  373947011@qq.com 谢谢

**Comment by fengjuan** [comment]
@NikiLee2016 同求分享，扫描识别很慢，446581985@qq.com 感谢

**Comment by xh2015** [comment]
@NikiLee2016 求分享 980916277@qq.com

**Comment by JokeenZhang** [comment]
可以使用华为统一扫码服务，这个也很快

**Comment by PLFENG** [comment]
> 我偶然拿到了别人公司内部的一个扫码库, 同样的低端机那个库只需要1秒, 而bga需要四五秒...我觉得还是和识别算法有关系

求分享249658231@qq.com

**Comment by nickalc** [comment]
你好，邮件已收到，谢谢

**Comment by wscjy** [comment]
您好，我已收到您的邮件，我会尽快给您回复。

**Comment by BaiPeiHe** [comment]
@NikiLee2016 可否分享一下,非常感谢，392275709@qq.com
